### ISSUE TITLE
500 Internal server error when getting versions

### ISSUE THREAD

**Issue by djtb2924** [everyday-as/gmodstore-php-sdk#1]
`Exception when calling AddonVersionsApi->addonsAddonIdVersionsGet: [500] Server error: `GET https://api.gmodstore.com/v2/addons/789/versions?with=with_example` resulted in a `500 Internal Server Error` response: { "message": "Server Error" }`

**Comment by TheodoorP** [comment]
Hey, 

I've tried to replicate it the following way:
```
$config = new \Everyday\GmodStoreSDK\Configuration();
$config->setApiKey('Authorization', $api_key);
$config->setApiKeyPrefix('Authorization', 'Bearer');

$addonsApi = new \Everyday\GmodStoreSDK\Api\AddonVersionsApi(null, $config);

var_dump($addonsApi->addonsAddonIdVersionsGet(789)->getData());
```

This worked fine for me, are you able to provide us with the code you used to try and fetch your addon's versions?

**Comment by TheodoorP** [comment]
500 due to a permission error, unrelated to the library so closing.
